// <auto-generated />
using System;
using GFood_CaseStudy.DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GFood_CaseStudy.DataAccess.Migrations
{
    [DbContext(typeof(GFoodContext))]
    [Migration("20220727200438_Add_Prices")]
    partial class Add_Prices
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Baskets");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Baskets_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Baskets_UpdatedAt");

                    b.ToTable("Baskets");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.BasketCouponCode", b =>
                {
                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CouponCodeId")
                        .HasColumnType("uuid");

                    b.HasKey("BasketId", "CouponCodeId")
                        .HasName("PK_BasketCouponCodes");

                    b.HasIndex("CouponCodeId");

                    b.ToTable("BasketCouponCodes");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.BasketProduct", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BasketId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProductId", "BasketId")
                        .HasName("PK_BasketProducts");

                    b.HasIndex("BasketId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_BasketProducts_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_BasketProducts_UpdatedAt");

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Campaigns");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Campaigns_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Campaigns_UpdatedAt");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Categories");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Categories_CreatedAt");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_Categories_ParentId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Categories_UpdatedAt");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.CouponCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Discount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPercentage")
                        .HasColumnType("boolean");

                    b.Property<int>("Quota")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_CouponCodes");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_CouponCodes_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_CouponCodes_UpdatedAt");

                    b.ToTable("CouponCodes");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Products");

                    b.HasIndex("Code")
                        .HasDatabaseName("IX_Products_Code");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Products_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_Products_UpdatedAt");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("ProductId", "CategoryId")
                        .HasName("PK_ProductCategories");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.ProductPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("PK_ProductPrices");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_ProductPrices_CreatedAt");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductPrices");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.BasketCouponCode", b =>
                {
                    b.HasOne("GFood_CaseStudy.Entities.Models.Basket", "Basket")
                        .WithMany("BasketCouponCodes")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFood_CaseStudy.Entities.Models.CouponCode", "CouponCode")
                        .WithMany("BasketCouponCodes")
                        .HasForeignKey("CouponCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("CouponCode");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.BasketProduct", b =>
                {
                    b.HasOne("GFood_CaseStudy.Entities.Models.Basket", "Basket")
                        .WithMany("BasketProducts")
                        .HasForeignKey("BasketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFood_CaseStudy.Entities.Models.Product", "Product")
                        .WithMany("BasketProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Basket");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Category", b =>
                {
                    b.HasOne("GFood_CaseStudy.Entities.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.ProductCategory", b =>
                {
                    b.HasOne("GFood_CaseStudy.Entities.Models.Category", "Category")
                        .WithMany("ProductCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GFood_CaseStudy.Entities.Models.Product", "Product")
                        .WithMany("ProductCategories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.ProductPrice", b =>
                {
                    b.HasOne("GFood_CaseStudy.Entities.Models.Product", "Product")
                        .WithMany("ProductPrices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Basket", b =>
                {
                    b.Navigation("BasketCouponCodes");

                    b.Navigation("BasketProducts");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Category", b =>
                {
                    b.Navigation("ProductCategories");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.CouponCode", b =>
                {
                    b.Navigation("BasketCouponCodes");
                });

            modelBuilder.Entity("GFood_CaseStudy.Entities.Models.Product", b =>
                {
                    b.Navigation("BasketProducts");

                    b.Navigation("ProductCategories");

                    b.Navigation("ProductPrices");
                });
#pragma warning restore 612, 618
        }
    }
}
